# Generated by Django 2.2.1 on 2019-05-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Camper_name', models.CharField(max_length=20, unique=True)),
                ('Password', models.CharField(max_length=10)),
                ('Age', models.IntegerField()),
                ('Years_Of_Exprience', models.IntegerField()),
                ('Interests', models.CharField(blank=True, choices=[('pure javascript front end', 'JS'), ('query javascript front end', 'JQuery'), ('angular javascript front end', 'Angular JS'), ('html', 'HTML'), ('css', 'CSS'), ('javascript back end', 'Node.JS')], max_length=20, null=True)),
            ],
        ),
    ]
