# Generated by Django 2.2.1 on 2019-05-30 05:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userss',
            name='Interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('pure javascript front end', 'JS'), ('query javascript front end', 'JQuery'), ('angular javascript front end', 'Angular JS'), ('html', 'HTML'), ('css', 'CSS'), ('javascript back end', 'Node.JS')], max_length=110, null=True),
        ),
    ]
