# Generated by Django 2.2.1 on 2019-05-30 08:19

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190530_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userss',
            name='Camper_name',
        ),
        migrations.AddField(
            model_name='userss',
            name='Camper_Name_Firstname',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='userss',
            name='Camper_Name_Lastname',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='userss',
            name='Personal_Image',
            field=models.ImageField(blank=True, null=True, upload_to='personal_image/%Y/%M/%D/'),
        ),
        migrations.AddField(
            model_name='userss',
            name='Programming_Languages',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('pure javascript front end', 'JS'), ('query javascript front end', 'JQuery'), ('angular javascript front end', 'Angular JS'), ('html', 'HTML'), ('css', 'CSS'), ('javascript back end', 'Node.JS'), ('C-bsaed', 'C/C++'), ('desktop C', 'C#'), ('objective C', 'Objective C'), ('JAVA SE', 'JAVA SE')], max_length=148, null=True),
        ),
        migrations.AlterField(
            model_name='userss',
            name='Interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BACKEND web development', 'BACKEND'), ('FRONTEND web development', 'FRONTEND'), ('desktop apps', 'DESKTOP APPLICATIONS'), ('android apps', 'ANDROID APPLICATIONS'), ('ios apps', 'IOS APPLICATIONS'), ('network apps', 'NETWORK APPLICATIONS'), ('security', 'SECURITY')], max_length=105, null=True),
        ),
    ]
